"""
Django settings for csa project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys
import djcelery
from celery.schedules import crontab
import dj_database_url


csa_env = os.getenv('CSA_ENVIRONMENT')
if csa_env is None:
    print(
        'Error: CSA_ENVIRONMENT environmental variable not set. '
        'Needs to be one of production, development, test')
    sys.exit()

# this picks the database from DATABASE_URL
DATABASES = {
    'default': dj_database_url.config()
}

if csa_env == 'production':
    # production specific
    # let's be explicit about this one
    DEBUG = False
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.sendgrid.net'
    EMAIL_HOST_USER = os.getenv('SENDGRID_USERNAME')
    EMAIL_HOST_PASSWORD = os.getenv('SENDGRID_PASSWORD')
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    if None in (EMAIL_HOST_USER, EMAIL_HOST_PASSWORD):
        raise ValueError(
            'you need to set environmental variables '
            'SENDGRID_USERNAME and SENDGRID_PASSWORD')
    SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
    # we don't do open-csa-ng.herokuapp.com here because review applications
    # get named open-csa-ng-pr-XX.herokuapp.com and requests to them fail.
    # We'll get our own domain eventually
    ALLOWED_HOSTS = ('.herokuapp.com',)
    SITE_URL = 'https://open-csa-ng.herokuapp.com'
elif csa_env == 'development':
    # development specific
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
elif csa_env == 'test':
    # test specific
    EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
else:
    raise ValueError(
        '"{}" not a valid CSA_ENVIRONMENT value'.format(csa_env))

# development or test specific settings
if csa_env in ('development', 'test'):
    SITE_URL = 'http://localhost:8000'
    SECRET_KEY = 'q_4b3b3nwm*$eu9l()w&@og2(o$*06c(rfvv!)$(5vm#ec2-lq'
    DEBUG = True
    # if not filled up by DATABASE_URL, default to local
    if not DATABASES['default']:
        DATABASES['default'] = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'csa',
            'USER': 'csa',
            'PASSWORD': 'p4ssw0rd',
            'HOST': '127.0.0.1',
            'PORT': '5432',
        }


# regardless of environment, we need this
DATABASES['default'].update({
    'CONN_MAX_AGE': 60,
    'ATOMIC_REQUESTS': True
})


# silly heroku won't pick up logs from stderr
log_level = os.getenv('LOG_LEVEL', 'INFO')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': log_level,
            'stream': sys.stdout
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': log_level,
        },
    },
}


djcelery.setup_loader()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Application definition

INSTALLED_APPS = [
    # builtin
    # third party but always before django.contrib.admin
    'bootstrap_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # third party
    'bootstrap3',
    'related_admin',
    'widget_tweaks',
    'kombu.transport.django',
    'djcelery',

    # our own
    'csa'
]


MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'csa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'csa.contexts.user_balance',
                'csa.contexts.registration_moderation',
            ],
        },
    },
]

WSGI_APPLICATION = 'csa.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'el-gr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

AUTH_PROFILE_MODULE = 'csa.models.UserProfile'
# how long to let user activate his account
ACCOUNT_ACTIVATION_DAYS = 7

PHONENUMBER_DEFAULT_REGION = 'GR'

# named-url provided by django_registration
LOGIN_URL = 'auth_login'

# TODO: serve this as static
BOOTSTRAP3 = {
    'css_url': '/static/css/lib/bootstrap.min.css',
    'jquery_url': '/static/js/lib/jquery.min.js',
    'javascript_url': '/static/js/lib/bootstrap.min.js'
}

# templated emails
TEMPLATED_EMAIL_FILE_EXTENSION = 'j2.mail'

EMAIL_SUBJECT_PREFIX = ''
DEFAULT_FROM_EMAIL = 'noreply@open-csa-ng.herokuapp.com'
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# this is merely list of users who get critical error emails by django
ADMINS = [('Dan Milon', 'i@danmilon.me')]
MANAGERS = ADMINS

# csa-specific
CSA_DELIVERY_WEEKDAY = 4
CSA_DELIVERY_TIME = 5
CSA_EMAIL_FROM = DEFAULT_FROM_EMAIL
CSA_TRANSACTION_CUT_PERCENT = 0.05
CSA_USER_REGISTRATION_MODERATION = True

BROKER_URL = 'django://'
# CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
CELERY_RESULT_BACKEND = 'djcelery.backends.database:DatabaseBackend'
CELERY_ACCEPT_CONTENT = ['pickle']

CELERYBEAT_SCHEDULE = {
    'ensure-order-periods': {
        'task': 'tasks.ensure_order_periods',
        'schedule': crontab(minute='*/5')
    }
}

BOOTSTRAP_ADMIN_SIDEBAR_MENU = True
